language: node_js
sudo: false
before_install:
  - "export CODECLIMATE_REPO_TOKEN=75f11dd1965d32050fe735ad6c96f374d74f437651fd7a0ea31fbb021f6c36da"
install:
  - "npm install grunt-cli codeclimate-test-reporter -g"
  - "npm install"
script:
  - "grunt ci"
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "iojs-v1"
  - "iojs-v2"
  - "iojs-v3"
cache:
  directories:
    - 'node_modules'
